### ISSUE TITLE
Some projects in the solution are not loading correctly 

### ISSUE THREAD

**Issue by GeorgiNik** [NikolayIT/TexasHoldemGameEngine#11]
The imported project "C:\Program Files (x86)\MSBuild\Microsoft\Portable\v5.0\Microsoft.Portable.CSharp.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  

http://puu.sh/l80yi/f53ce1a28d.png

**Comment by kiko81** [comment]
Probably you'll find solution [here](https://telerikacademy.com/Forum/Questions/181570/%D0%97%D0%B0%D0%BF%D0%B8%D1%81%D0%B2%D0%B0%D0%BD%D0%B5-%D0%B7%D0%B0-%D0%BE%D1%82%D0%B1%D0%BE%D1%80%D0%BD%D0%B0%D1%82%D0%B0-%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0-%D0%BF%D0%BE-%D0%A1%D1%82%D1%80%D1%83%D0%BA%D1%82%D1%83%D1%80%D0%B8-%D0%B4%D0%B0%D0%BD%D0%BD%D0%B8-%D0%B8-%D0%B0%D0%BB%D0%B3%D0%BE%D1%80%D0%B8%D1%82%D0%BC%D0%B8-2015)

**Comment by NikolayIT** [comment]
https://telerikacademy.com/Forum/Questions/181570/%D0%97%D0%B0%D0%BF%D0%B8%D1%81%D0%B2%D0%B0%D0%BD%D0%B5-%D0%B7%D0%B0-%D0%BE%D1%82%D0%B1%D0%BE%D1%80%D0%BD%D0%B0%D1%82%D0%B0-%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0-%D0%BF%D0%BE-%D0%A1%D1%82%D1%80%D1%83%D0%BA%D1%82%D1%83%D1%80%D0%B8-%D0%B4%D0%B0%D0%BD%D0%BD%D0%B8-%D0%B8-%D0%B0%D0%BB%D0%B3%D0%BE%D1%80%D0%B8%D1%82%D0%BC%D0%B8-2015#forum-post-181953
