### ISSUE TITLE
Implement minimum bet and raise amount

### ISSUE THREAD

**Issue by todorm85** [NikolayIT/TexasHoldemGameEngine#21]
You have to at least double the previous bet in no-limit Texas Holdem when you make a raise. The least you can bet is the same amount as the big blind.

E.x.lets assume the blinds are 50/100 in a no limit game. Player 1 who is first to act after the big blinds (pre flop) raises to 300. With 100 blinds this means that the actual raise is 200. The minimum that player 2 (Wood) could raise to is therefore 500 (300+200).

The rules are the same for all betting rounds. But in each new betting round the minimum bet is always goes back to the same size as the big blind.

**Comment by NikolayIT** [comment]
This is known issue. Currently we don't have time to implement it and the AI battles will be played that way.

**Comment by dalorveen** [comment]
The minraise is now implemented
