### ISSUE TITLE
Straight optimization proposal

### ISSUE THREAD

**Issue by kiko81** [NikolayIT/TexasHoldemGameEngine#3]
better list clear than new list - line 97

**Comment by NikolayIT** [comment]
Will be fixed. Thanks! Create pull request next time.

**Comment by kiko81** [comment]
this way not the highest possible straight is returned but the lowest instead - will fix it

**Comment by NikolayIT** [comment]
Add unit tests (for regression)

**Comment by kiko81** [comment]
!!! line 134 - var straightCards = cards.Select(x => (int)x.Type).ToList();  - returns duplicates

renaming proposal: CompareTwoHandsWithHighCard => CompareKickers

**Comment by NikolayIT** [comment]
Open new issues for every single bug.

**Comment by NikolayIT** [comment]
When comparing straights there are objects of type `CardType` so `Ace` is expected.

**Comment by kiko81** [comment]
Mean if compare e.g. 2nd cards only  - no `Ace` possible there - `Ace` may be first or last only

**Comment by NikolayIT** [comment]
What about this case:
    new[]
        {
            CardType.Six, CardType.Five,
            CardType.Four, CardType.Three,
            CardType.Two
        },
    new[]
        {
            CardType.Five, CardType.Four,
            CardType.Three, CardType.Two,
            CardType.Ace
        }

**Comment by kiko81** [comment]
e.g. 2nd cards: five > four => first wins  
       3rd cards: four > three => first wins
       4th cards....... 
`Ace`s can be in the beginning or the end of hand - not in the middle - don't check ends - any middle will do the trick

**Comment by NikolayIT** [comment]
I've got the idea but current solution is `O(n)` and the one you suggest requires sorting which will be `O(n * log(n)`.

**Comment by kiko81** [comment]
thought they come sorted from hand evaluator, from tests come shuffled - anyway U know better :+1:
